export const ActionTypes = {
  SET_SONGS: "SET_SONGS",
  SET_SEARCH: "SET_SEARCH",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SET_POSTS: "SET_POSTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
